### ISSUE TITLE
从网络获取的对象属性是数字，可以动态添加吗

### ISSUE THREAD

**Issue by aefgijn** [Jay-huangjie/FunnelView#2]
自定义描述文字时，最后的数字，可以动态添加吗，方法是？

**Comment by Jay-huangjie** [comment]
调用setChartData将数据源设置进去就好了呀，数字是你的数据源里面自己定义的，你想动态添加直接把数据源更新一下就好了

**Comment by aefgijn** [comment]
> 调用setChartData将数据源设置进去就好了呀，数字是你的数据源里面自己定义的，你想动态添加直接把数据源更新一下就好了

数据源必须实现那个接口才行 类似例子里的？

**Comment by Jay-huangjie** [comment]
不是很明白你的需求，你如果是想将描述文字的值按照你自己的规则来改变的话可以使用`addCustomLabelCallback` 接口来接管描述文字的绘制，你想画什么颜色的有没有数字什么的或者用哪个数据源都随你了，例如我的那个自定义描述里的数字就是用的`num`字段而不是用的接口的`label`字段

**Comment by aefgijn** [comment]
可否添加其他的联系方式，远程指导一下，这边还是有点问题

**Comment by Jay-huangjie** [comment]
加我Q：289223562
